name: Compress and Upload Images

on:
  push:
    branches:
      - main
    paths:
      - 'src/img/**.jpg'
      - 'src/img/**.jpeg'
      - 'src/img/**.png'
      - 'src/img/**.webp'

jobs:
  compress-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # 获取最近两次提交，用于比较文件更改

      - name: Get modified files
        id: modified_files
        run: |
          ADDED=$(git diff --diff-filter=ACMR --name-only HEAD^ HEAD -- 'src/img/')
          DELETED=$(git diff --diff-filter=DR --name-status HEAD^ HEAD -- 'src/img/' | awk '$1=="D" || $1=="R"{print $2}')

          echo "ADDED_MODIFIED=$ADDED" >> $GITHUB_ENV
          echo "DELETED_OR_RENAMED=$DELETED" >> $GITHUB_ENV

          if [ -n "$ADDED" ]; then
            echo "has_add_or_mod=true" >> $GITHUB_OUTPUT
          fi
          if [ -n "$DELETED" ]; then
            echo "has_delete_or_rename=true" >> $GITHUB_OUTPUT
          fi

      - name: Compress images
        if: steps.modified_files.outputs.has_add_or_mod == 'true'
        uses: calibreapp/image-actions@main
        with:
          compressOnly: true
          ignorePaths: 'node_modules/**,build'
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Install coscmd
        run: pip install coscmd

      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: Upload compressed images to COS
        if: steps.modified_files.outputs.has_add_or_mod == 'true'
        run: |
          IFS=$'\n'
          for FILE in $ADDED_MODIFIED_FILES
          do
            echo "Uploading $FILE to COS"
            coscmd upload $FILE blog/friends/
          done

      - name: Delete removed or renamed files from COS
        if: steps.modified_files.outputs.has_delete_or_rename == 'true'
        run: |
          IFS=$'\n'
          for FILE in $DELETED_OR_RENAMED
          do
            echo "Deleting $FILE from COS"
            coscmd delete "blog/friends/$FILE"
          done
        
